### ISSUE TITLE
Boolean Filter false option is not working.

### ISSUE THREAD

**Issue by philipzweihoff** [jangemue/TableBundle#14]
I've used a boolean filter on the attribute "foo":
->add('boolean', 'foo', array(
	'label' => 'Foo',
	'true' => 'Present',
	'false' => 'Not Present',
	'reset_label' => 'All',
	'widget' => 'select',
	'attr' => array('class' => 'form-control'),
	'operator' => FilterOperator::EQ
))

But when the option "Not Present" is selected, the results contain all entries including true and false foo attributes.

**Comment by jangemue** [comment]
Using a reset label on a boolean filter is senseless, i will remove this option at the next version. A boolean filter can only have two states: true or false, there is no possibility to reset a boolean filter (what should that mean? confusing, i know). Try to use the valued filter or use the boolean with only true and false :-)

**Comment by philipzweihoff** [comment]
I think it is worth it!
The reset option can be used if the table should contain all entries true and false.
The ticked has been created, because the false option causes the result of all instead of just the false entries.
And in addition to this, the removing of the reset_label option doesn't cause any improvement.

**Comment by jangemue** [comment]
You're right, I was convinced, that the boolean filter is presented by a checkbox, neither a choice- nor a select- input. I will try to fix that as bugfix for version 1.2 :-)
