### ISSUE TITLE
Date Filter

### ISSUE THREAD

**Issue by philipzweihoff** [jangemue/TableBundle#20]
The usage of date filters causes the exception: 
Warning: strlen() expects parameter 1 to be string, object given

In:

jgm/tablebundle/JGM/TableBundle/Table/Filter/AbstractFilter.php at line 375

Code:

return isset($this->value) && strlen($this->value) > 0;

If $this->value is an instance of DateTime, the strlen Method throws the exception.
An alternative IF could be a solution.

**Comment by jangemue** [comment]
Yeah, you're right. The DateFilter should override the isActive() function. Thanks for reporting. Will fix this, once #21 is solved.

**Comment by jangemue** [comment]
Fixed for 1.2 and 1.3
