### ISSUE TITLE
Time-Out in SimpleLimitStrategy

### ISSUE THREAD

**Issue by philipzweihoff** [jangemue/TableBundle#21]
The initial load of a Table causes a Timeout in the Browser.

In class:
jgm/tablebundle/JGM/TableBundle/Table/Pagination/Strategy/SimpleLimitStrategy.php at line 45

It seems that the iterative use of the in_array method causes this time consumtion.

**Comment by jangemue** [comment]
Can you show me the configuration of your table type? How much data do you expect?

Please mention the version. Thanks

**Comment by philipzweihoff** [comment]
Sry for the poor information. Here are the details:

- Version 1.3
- 1000 entries

And here are the snippets:

`public function configurePaginationOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults(array(
			'max_pages' => "20",
		));
	}`

`public function configureOrderOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults(array(
			'empty_column' => 'foo.bar',
			'empty_direction' => 'asc',
			'class_asc' => 'glyphicon glyphicon-arrow-up',
			'class_desc' => 'glyphicon glyphicon-arrow-down'
		));
	}`

`public function getDataSource(ContainerInterface $container)	{
		return new EntityDataSource('FooBarBundle:Bar', function(\Doctrine\ORM\QueryBuilder $queryBuilder) {
			$queryBuilder->where('t.name = :name')->setParameter('name','foo');
		});
	}`

`public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults(array(
			'empty_value' => "Nothing here",
			'attr' => array('class' => 'table')
		));
	}`

**Comment by jangemue** [comment]
Fixed for 1.2 and 1.3
