### ISSUE TITLE
Postgres filter query issues

### ISSUE THREAD

**Issue by beezischillin** [jangemue/TableBundle#27]
When you use a Postgres database, filtering generates invalid queries when trying to filter against fields that don't support the LOWER function, like boolean, etc.

Is there any hope for a fast fix?

> An exception occurred while executing 'SELECT count(t0_.id) AS sclr_0 FROM tl_user t0_ WHERE (LOWER(t0_.enabled) LIKE ?)' with params ["%1%"]:
> 
> SQLSTATE[42883]: Undefined function: 7 ERROR: function lower(boolean) does not exist
> LINE 1: ...T count(t0_.id) AS sclr_0 FROM tl_user t0_ WHERE (LOWER(t0_....
> ^
> HINT: No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by jmuehlig** [comment]
Thanks for your report. Is it an option to use another filter operator than `FilterOperator::LIKE` (it is the default)? I think the `FilterOperator::EQ` (which is released under namespace `JGM\TableBundle\Table\Filter`) should be better for that filter. If not, please tell me for implementing a bugfix.

**Comment by beezischillin** [comment]
Awesome, thank you, I'll try it tomorrow when I get back at work!

**Comment by beezischillin** [comment]
Great news! Seems to work right with the EQ operator! 

If I may have one suggestion: might be worth making EQ the default operator for boolean fields, since it doesn't make much sense to use LIKE for those anyway, or at least adding this bit of notice to the documentation.

Anyhow, thank you and keep up the great work!

**Comment by jmuehlig** [comment]
Changing the filters default options, like the default operator, is not possible at the current version. You can change it yourself by manipulating the sources (`JGM\TableBundle\Table\Filter\AbstractFilter` in `setDefaultOptions`), but you may loose it by updating to the next versions. 

If you add an issue for that, I will do my best to add this to the next version, but at the moment there is no time for that.

**Comment by beezischillin** [comment]
No worries. I don't mean to impose on your time, was just an idea to make it more compatible with databases other than mysql. Thank you for your help, really nice work on the bundle!
